# V0rtexOS — pacman.conf para ARM64 (aarch64)
[options]
HoldPkg      = pacman glibc
Architecture = aarch64
CheckSpace
SigLevel     = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist-aarch64

[extra]
Include = /etc/pacman.d/mirrorlist-aarch64

[blackarch]
Server = https://blackarch.org/blackarch/$arch
